{% set name = "scikit-beam" %}
{% set version = "0.0.16" %}
{% set sha256 = "9f832aadc084089c2a4b9ef2038ec1b692f5404e3ab5b7d0a9fe50dc84446147" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  fn: {{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  script:
    - python setup.py build_ext -i
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - autoconf  # [osx]
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - setuptools
    - six
  run:
    - python
    - lmfit =0.8.3
    - scikit-image
    - scipy
    - six
    - xraylib
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - skbeam
    - skbeam.io
    - skbeam.core
    - skbeam.core.accumulators
    - skbeam.core.constants
    - skbeam.core.fitting
    - skbeam.core.fitting.base
    - skbeam.ext
    - skbeam.core.fitting
    - skbeam.core.constants.xrf
    # has linux native library imports  # [not win]
    - skbeam.ext.ctrans  # [not win]

about:
  home: http://scikit-beam.github.io/scikit-beam
  license: BSD 3-Clause
  summary: Data analysis algorithms for X-Ray, Neutron and Electron sciences
  license_file: LICENSE
  license_family: BSD
